# Generated by Django 3.2.8 on 2021-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('logo', models.URLField(default='https://ingressive.org/wp-content/uploads/2020/05/I4G-Logo-Color-Cropped.png')),
            ],
        ),
    ]
