# Generated by Django 3.2.8 on 2021-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intern', models.ManyToManyField(blank=True, related_name='intern_stack', to='app.Intern')),
            ],
            options={
                'verbose_name': 'stack',
                'verbose_name_plural': 'stacks',
            },
        ),
    ]
