# Generated by Django 3.2.8 on 2021-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_intern_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
